scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        invert: false
        max_x: 100.0
        max_y: 10.0
        max_z: 1.0 
        min_x: -0.2
        min_y: -10.0
        min_z: -1.0

